btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1768330868.e81401c0b.linux.amd64.tgz:
  size: 929206645
  object_id: 3f18f21b-9204-433d-6b29-5f530f5afd44
  sha: sha256:a78c4ed219fb27566809475ab257c4316a76030e3cee455876319721d62a9317
concourse/concourse-7.14.3+dev.1768330868.e81401c0b.windows.amd64.zip:
  size: 241499180
  object_id: 247660ba-d365-48eb-53e0-4f828b90cf9d
  sha: sha256:80d58e6463a367589820120f79817c1ca4940f70874ef22b5505d9ccb1c5da64
