btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765345054.432a9fbb1.linux.amd64.tgz:
  size: 952119189
  object_id: d8b1a18a-1a47-4cea-682e-51042804e876
  sha: sha256:78f5067d2dd7df491c04b50815e96c925c9295c42f422e46ed2ba340d10d440a
concourse/concourse-7.14.3+dev.1765345054.432a9fbb1.windows.amd64.zip:
  size: 250607271
  object_id: 9e5fb884-fcb2-44bc-58fb-c3bff868ef74
  sha: sha256:97a39c15536f060e9f131ba8b8d5efe2b19ab84a87867457a81512913101a70a
