btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1766084630.a785c6ea9.linux.amd64.tgz:
  size: 951858553
  object_id: fc20bb88-3fee-4b8a-5132-6bf1341b9db5
  sha: sha256:c35fa53e7abf39c44987e8da44de1c8ab0eca3ae777903570f48aa162449cb95
concourse/concourse-7.14.3+dev.1766084630.a785c6ea9.windows.amd64.zip:
  size: 250629349
  object_id: 8ef68a77-2224-4cda-67e5-5d4e5ce03ed8
  sha: sha256:2aabbddb9c43a32ff6144abc3098ce605da26643d26474d2e0711a4d149b0ad0
