btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1764720833.c94af1ab0.linux.amd64.tgz:
  size: 951715160
  object_id: 53d5eb20-c94f-462e-425d-1b5ccf231ead
  sha: sha256:7453e755526e5d83dc67d612e0a6a75bdd315570a53b679d3cebeda4ddb03a02
concourse/concourse-7.13.2+dev.1764720833.c94af1ab0.windows.amd64.zip:
  size: 251222337
  object_id: 0bdd6cd2-122b-490e-5930-13bd6b4be843
  sha: sha256:4869940d866d80a68700fe29902ae5e23ec4660e20990fb7535519a0376289c6
