btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.29+e9b986ce9.linux.amd64.tgz:
  size: 937658887
  object_id: d32481eb-b406-44c6-6fde-5a0e827fd603
  sha: sha256:3baea30437cecca35fda17257c100279d0084e6ccadec1109417b97c3c7e7bc9
concourse/concourse-7.14.4-rc.29+e9b986ce9.windows.amd64.zip:
  size: 244428360
  object_id: a00acaa8-690f-4fe4-5d57-fe28a78f0337
  sha: sha256:09d71d546a1a408ffe9e96105397ca6128848660ee338deb16ce1446d69d43ff
