btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.22+dafad0f96.linux.amd64.tgz:
  size: 936596316
  object_id: 25e908e7-06cf-44da-4dcb-395b757cc5e9
  sha: sha256:a2b2ea57fbe666439b7ef5a8d4f76a126e3df9befac4c270e83cab6b9e7cccab
concourse/concourse-7.14.4-rc.22+dafad0f96.windows.amd64.zip:
  size: 244430469
  object_id: 03d7f957-d9bc-4f06-71b9-1dbc875ad78e
  sha: sha256:3134da5dd084fef7a0ee907e1a8e028357a85fd7cf13d762ee7f5a60c0017c11
