btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.2+dev.1772134266.adfcfb272.linux.amd64.tgz:
  size: 919004262
  object_id: da4d7d5c-938a-482b-7999-e7e092f5fbc6
  sha: sha256:dc67b96be585429c3263bd18f68677ffb3f3cdda287d5812f5ee72a84787305d
concourse/concourse-8.0.2+dev.1772134266.adfcfb272.windows.amd64.zip:
  size: 251883056
  object_id: d6e69116-b56e-4ba1-4433-15c274e30dd6
  sha: sha256:78e069c7ca2d1db4dc118cbb24d82590d2de5f8a8bfb93884b6232be1ab70d09
