btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767829606.a785c6ea9.linux.amd64.tgz:
  size: 939123649
  object_id: 21cb9776-8519-49ff-797e-ded60df3eec9
  sha: sha256:9520ab4f488ca2ca37c28869a3e3ccbccb4707be2a18725f012fc8a3b29a635c
concourse/concourse-7.14.3+dev.1767829606.a785c6ea9.windows.amd64.zip:
  size: 250629437
  object_id: 85d99399-726d-40cd-6ee3-decfa2a13cd5
  sha: sha256:5d9be374a432ca710b5db1a6492a7f66e0b2396fecc3e9429e8ded68944db83e
