btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1762479465.c67692d7e.linux.amd64.tgz:
  size: 942914367
  object_id: a517bd24-aac3-410d-5352-6769f70f88c1
  sha: sha256:a7750cfcbd854d58e33bec29a65f258bfde22d272de9539926cba17b24c904a3
concourse/concourse-7.13.2+dev.1762479465.c67692d7e.windows.amd64.zip:
  size: 249593634
  object_id: bd5893ae-0a43-4423-53cd-5c5cdb51eaa6
  sha: sha256:4252a9ad51a1879d9bda5f13effb53c72a7475a008b0c96e7f112fddf4609b8a
