btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.24+e9b986ce9.linux.amd64.tgz:
  size: 936682867
  object_id: d00155aa-59a0-489a-6a94-a059ea4ea10e
  sha: sha256:044aefffa0540c984f081c4176530ac3b76bdf7cf172f4a81e95766537bb01dc
concourse/concourse-7.14.4-rc.24+e9b986ce9.windows.amd64.zip:
  size: 244427609
  object_id: 9cf2d267-720c-412c-763a-86cdb94d5fb3
  sha: sha256:fb6d7d41da931f453046b4ed7c082eb9924aadbbaeb5b4875685d64663515607
