btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.2+dev.1771631112.cd61cbd24.linux.amd64.tgz:
  size: 918946897
  object_id: bafb699b-1bdc-46e4-5443-fdec2f74ee19
  sha: sha256:b3e9b11e782076ee2f48df5f4934240b876c519895252244dc9e4a5f85824ef0
concourse/concourse-8.0.2+dev.1771631112.cd61cbd24.windows.amd64.zip:
  size: 251883409
  object_id: b66bc675-c99a-43a2-6ce9-b8ee6850ae6a
  sha: sha256:0110d0847eae8d7311a137696a9aaeea98d1ef1737d679f0816d7f49e2e8aefb
