btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.30+e9b986ce9.linux.amd64.tgz:
  size: 937667622
  object_id: 35aefa92-40ec-4461-66f0-c061bdcac3b8
  sha: sha256:f8fb30faced128adbf2a7f985c99ef994164fefffdb121c17edb117034122a7d
concourse/concourse-7.14.4-rc.30+e9b986ce9.windows.amd64.zip:
  size: 244428007
  object_id: 0349e07f-715d-4746-7f94-1eb27b33726f
  sha: sha256:1a41c0ff362ea7d5e139ea4b77423c2e937923f3d492d6334935f44526ea2e1f
