btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.14+34f038301.linux.amd64.tgz:
  size: 936598080
  object_id: df99c3fd-fd2f-497d-716b-aa05d15223b5
  sha: sha256:63b59b02407c0ff36fd64387eea901ff8983aac8cfa6959190a39354a10466b4
concourse/concourse-7.14.4-rc.14+34f038301.windows.amd64.zip:
  size: 244414360
  object_id: 11d9c736-ac1e-4e73-6a14-3b80580999af
  sha: sha256:3202e4e55eaa63044cd76e311c73f0be2e87aac551ee81ee9cc42f2f526a246c
