btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1764713610.c94af1ab0.linux.amd64.tgz:
  size: 951589704
  object_id: 95b2f612-9930-4df3-4009-4d95944d46fe
  sha: sha256:e39c9599afaae61b79a33d2872df28daea359e6a3f4734de2d7ec55f721e4822
concourse/concourse-7.13.2+dev.1764713610.c94af1ab0.windows.amd64.zip:
  size: 251223225
  object_id: c38e06ac-0477-44b1-582a-f9cb490c3bf2
  sha: sha256:effc26b7ce27ff8d7876319d9fcfc7313edc11012335ac3a53b44b6d773725b7
