btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767730671.a785c6ea9.linux.amd64.tgz:
  size: 937737716
  object_id: 1abe996f-0627-4cf8-4091-92d16e533d6b
  sha: sha256:f1a4212b5962457308dfc762a5d08559bef8290f02743a4a2afcdf96242c0e3c
concourse/concourse-7.14.3+dev.1767730671.a785c6ea9.windows.amd64.zip:
  size: 250629473
  object_id: 356ef77e-f029-4aef-501f-957ca3c1ca9b
  sha: sha256:93651778c983bb0a9556edd6838d5c0e5aeafb2393cd08bb3d865490a7dd0696
