btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1762240077.c67692d7e.linux.amd64.tgz:
  size: 939592277
  object_id: acc4cd71-bbcb-438a-5868-1587d2d92753
  sha: sha256:907a6557b32683ae366be763e7905bf3d306aed05d6ea09f2287bc80cbb1e13e
concourse/concourse-7.13.2+dev.1762240077.c67692d7e.windows.amd64.zip:
  size: 249596465
  object_id: 56f2c451-4666-4ff3-4d82-300a7cc6f0a5
  sha: sha256:b82d3142afb93aec347bcd526d050864d154638b882e310f3f9cb9d31faaa42e
