btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.45+e9b986ce9.linux.amd64.tgz:
  size: 937847533
  object_id: 48a8b3a9-9f77-41fc-5758-69171cde4f29
  sha: sha256:432980fe0eaa7b153cd67ee8ed2c6d30772c8c7a3ded3f94bc3ada03d1e5b8bf
concourse/concourse-7.14.4-rc.45+e9b986ce9.windows.amd64.zip:
  size: 244430580
  object_id: 89e7c9af-8144-44e5-66e5-0b26c14010da
  sha: sha256:2649c20ec2c878f6b8baa5480ed59b86629053eca43fe740cf7d74777dec755e
