btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767818104.a785c6ea9.linux.amd64.tgz:
  size: 938027903
  object_id: 5ccc2f04-481d-4b76-5227-057295273dc9
  sha: sha256:2de834b56fa724247514df7bafe2e54dc0119bf586bff223862f3e38e90df5ec
concourse/concourse-7.14.3+dev.1767818104.a785c6ea9.windows.amd64.zip:
  size: 250629615
  object_id: 17786f75-b27b-4e68-4457-73f0c545e54a
  sha: sha256:f91732d883b5331e8127ab83ec9324ff5891e597b9a79fa4373bc29a2f8745dc
