btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.2-rc.18+caf63a4d6.linux.amd64.tgz:
  size: 929141534
  object_id: 1f952f7a-68d6-4ea8-72c8-8a64bb1fb11a
  sha: sha256:734551b58a49374c49019c0c7e5d74aec054cc4898688a9cd045f4b7df66e283
concourse/concourse-8.0.2-rc.18+caf63a4d6.windows.amd64.zip:
  size: 241548662
  object_id: 85209746-b479-428d-65ec-02dea7a7726c
  sha: sha256:8935fe3f9d2e1ad47c25764831b4a98da4aba3b72c81449e923784e31d4e1204
