btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767740601.a785c6ea9.linux.amd64.tgz:
  size: 937853890
  object_id: e044772d-c9e2-4798-4d20-62f4b8bdc548
  sha: sha256:82ea67962f091cfb625deb4c1e65bcf3074c48cdbf29f356bd4637b52b74da67
concourse/concourse-7.14.3+dev.1767740601.a785c6ea9.windows.amd64.zip:
  size: 250629926
  object_id: 0b898cf4-ef09-4f40-5e27-356f0fefae2c
  sha: sha256:4c42c95cecd26dc3393226319ea0a72f2e0de135f0ec922e0c2a888831c2600e
