btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1770083627.f6795d8b5.linux.amd64.tgz:
  size: 916719338
  object_id: 93700e39-4f93-482c-5cf2-4ccb78d847c2
  sha: sha256:0bf18aa0873d85fe31936e65187c6ff7fddf3cfc50347929133c2195123b099f
concourse/concourse-8.0.1+dev.1770083627.f6795d8b5.windows.amd64.zip:
  size: 241530745
  object_id: a2aad7d5-5cb9-4280-7dfb-61f08d8f6645
  sha: sha256:ec1c97988db8bf5b58913f565473150603be5b17f4e82a2cf9a520de4c64ab00
