btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.21+34f038301.linux.amd64.tgz:
  size: 936574645
  object_id: efd0a517-d4e7-47df-7fb5-c438f7b2023b
  sha: sha256:741b0f3709d5797732c33b23d4af6613bdef59e9ad8629a4ed17287745ccdfd9
concourse/concourse-7.14.4-rc.21+34f038301.windows.amd64.zip:
  size: 244430614
  object_id: 4d6f8f5c-a384-4c6f-6d89-106999bb2622
  sha: sha256:6313bc1aec077d558b759bcbd41e17f274aba1a7a78fc6d35fc5481ed4b594a7
