btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.36+e9b986ce9.linux.amd64.tgz:
  size: 937612001
  object_id: 0d131188-a0b1-41ef-7f3b-5e2ed162463a
  sha: sha256:c92cacb10704d712507e144647905e5c879fbb278dac538c4c9607f72d2ba7e4
concourse/concourse-7.14.4-rc.36+e9b986ce9.windows.amd64.zip:
  size: 244429544
  object_id: d2ae3674-d17f-4df6-46b3-6591694574b4
  sha: sha256:54dd935d7bf33097c2867a5d9d0aae652e582fc20f364cefd187b245d8ea8244
