btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1769107320.821ecf1db.linux.amd64.tgz:
  size: 929296085
  object_id: 7e3bc99f-6085-4cce-5c9b-ce4b301181a8
  sha: sha256:5e9dff87d68568fe4fc726a00c86df26c1cb52495a2dff2898dc65fe33118f44
concourse/concourse-8.0.0+dev.1769107320.821ecf1db.windows.amd64.zip:
  size: 241536973
  object_id: 9affe7b9-e784-4762-6180-a4883add15dd
  sha: sha256:1621607936105f1af88bb9d965aff4006ced580bb9132845204869c9586af3c7
