btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767320866.a785c6ea9.linux.amd64.tgz:
  size: 937395103
  object_id: ada6f72b-2ab0-401f-44cf-811cb3ae04f7
  sha: sha256:5cecab2617a4c903811efeca07219960b248ae5acec885f5f7c0fbd34eae03b7
concourse/concourse-7.14.3+dev.1767320866.a785c6ea9.windows.amd64.zip:
  size: 250630101
  object_id: ba34cbfd-e52b-487e-4731-060962779504
  sha: sha256:7e78ced350ec2b7887c990755ce3f7e35e96887b1b9e06176035445d98bcd1f0
