btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1771454988.2947128ee.linux.amd64.tgz:
  size: 918772554
  object_id: ebd003ee-8692-4c6d-7b5a-2a098a734a9c
  sha: sha256:845326cbe705503205a55c460a98a8a74dbb569f7caf0234d20b42d3c069abd6
concourse/concourse-8.0.1+dev.1771454988.2947128ee.windows.amd64.zip:
  size: 251696752
  object_id: 33a3f33c-9c2f-412c-59b8-d9fedac464b5
  sha: sha256:d2e338553f27b1c6fe2195f7d8effc1dd032d5e0411d90ec0a6611c5c9aa38ed
