btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1769519006.f6795d8b5.linux.amd64.tgz:
  size: 928994527
  object_id: f5dd23f2-c17d-4b93-601e-b46fbb3f5942
  sha: sha256:9df8ec70acf4a039ca0ac7b6999db0d2f95f76f08b311e2499ab9ba3ef79d3fe
concourse/concourse-8.0.0+dev.1769519006.f6795d8b5.windows.amd64.zip:
  size: 241530032
  object_id: 604ca465-23b6-494d-664c-9e2359ec9723
  sha: sha256:b396152f17986eee9c4ea80b8f3c87fae29eac386b6455780e0514e68aafff6e
