btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1763759446.750ce8b64.linux.amd64.tgz:
  size: 959203345
  object_id: e95ca7df-1437-451b-773f-f426104495f1
  sha: sha256:a7b7149317bda63b9bc94c33f390e2610fff0c6309196812a90b032dc3e2f600
concourse/concourse-7.13.2+dev.1763759446.750ce8b64.windows.amd64.zip:
  size: 249624580
  object_id: 270f666e-f22e-481b-66ad-3fa9e122db90
  sha: sha256:3daeed094a297500463ad545a1c169ec0c06f5871dbf3ae812bb37b90942e9b3
