btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1763749753.750ce8b64.linux.amd64.tgz:
  size: 959207171
  object_id: 0ed6a39f-010d-4982-4153-1028e5c79968
  sha: sha256:58ac6b04ae57339e82098ef4399900cfe6ddb1fefb8ba7ac0bf0b6e29aaed476
concourse/concourse-7.13.2+dev.1763749753.750ce8b64.windows.amd64.zip:
  size: 249624990
  object_id: 3aca6230-c54c-4bbf-5a19-0c425696b8b6
  sha: sha256:fc5d6a357ca9b8f2b4c629bdba993ebdf850b7acf8afe7cd4792777c5c709c77
