btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765804990.79e7b5411.linux.amd64.tgz:
  size: 951741383
  object_id: a828c297-a1b3-43ec-7f95-e180e2139800
  sha: sha256:c1e0974ef8ebd0d687a195e81d21ea1aaad1ed39cbc36a8970701ad2acc5515c
concourse/concourse-7.14.3+dev.1765804990.79e7b5411.windows.amd64.zip:
  size: 250632656
  object_id: 45daa471-d917-45d4-5dc6-69dcda67d965
  sha: sha256:a94935d5fc32a72f8f244162f2638a077d0fa998c44ffc142484d98bf259d2d2
