btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1768950313.d5bf4d4d8.linux.amd64.tgz:
  size: 929226810
  object_id: d6ec7e43-5d79-49a6-69ea-92eb9b51f2f3
  sha: sha256:95228a4944f71f6db08977d386560199a2933aa18d8ee8887fa739d5c0afdfca
concourse/concourse-8.0.0+dev.1768950313.d5bf4d4d8.windows.amd64.zip:
  size: 241535061
  object_id: ee27200d-b6f8-4683-6878-1d282022558e
  sha: sha256:2140d9f1bf0fe9bbd175a95dc2db6a03a7cbdde60cfb1c575edc6ab5b1d85772
