btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1768340169.e81401c0b.linux.amd64.tgz:
  size: 929215759
  object_id: 50e1f2fc-cec2-409b-615c-096b983e4a3a
  sha: sha256:d05c00a2bc4527687913e1ed39a39898fb2b0427953a1bd4b362e0f92070e310
concourse/concourse-7.14.3+dev.1768340169.e81401c0b.windows.amd64.zip:
  size: 241499804
  object_id: 1d942896-9a4c-475c-451c-90569cd71a97
  sha: sha256:f6259ee57318702a72d32459a33bcb47e73a53bbae1e339aaf1306be0e72b327
