btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767736321.a785c6ea9.linux.amd64.tgz:
  size: 937653946
  object_id: b509ae07-b194-48ea-5ec5-d817df47e39e
  sha: sha256:5aa6d68e6c51f05afe4770315a8eaa8f9641e510467692728d1094870d4cdf87
concourse/concourse-7.14.3+dev.1767736321.a785c6ea9.windows.amd64.zip:
  size: 250630057
  object_id: 9b28489e-8115-4015-796b-74acb8651eea
  sha: sha256:1e7d4a56d1a094cecb8b45b4ca141d71a7d14360a6c77d083699edd1680c5b89
