btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767096170.a785c6ea9.linux.amd64.tgz:
  size: 937390066
  object_id: c2cf4ec1-ccce-4a92-67f3-77bb0b092599
  sha: sha256:ed029d45bd5a7cf33fd8d130cec8137760eefde6afeac7f229ae13090b7a90d5
concourse/concourse-7.14.3+dev.1767096170.a785c6ea9.windows.amd64.zip:
  size: 250630472
  object_id: 9dfe8356-b6ef-425e-42af-6eb39002cbd4
  sha: sha256:a7f2c8436ff77071583e958419ad6de0a1b8fca7659be720909aced9f14abce1
