btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.2-rc.13+caf63a4d6.linux.amd64.tgz:
  size: 929167364
  object_id: 1b40aa77-3b15-4ee9-769d-e3f0a4825782
  sha: sha256:c57eaf906bb817a5f81727ca448d18248e82ad8464f3146df5c56d1d2ef8d7a7
concourse/concourse-8.0.2-rc.13+caf63a4d6.windows.amd64.zip:
  size: 241548808
  object_id: 32a5e909-05dc-4eb4-7ace-93f98463b8a0
  sha: sha256:011c983c38844f8e5a1d81cbb0501cd50e16107777e59788eee64cae6a3088a8
