btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767116987.a785c6ea9.linux.amd64.tgz:
  size: 937396365
  object_id: 744cd1c7-498e-44d8-5c36-cb4144b201c9
  sha: sha256:03d2ccf44c2650f1eae706baa6426f9687b3d1266c1bc7bc7bd3be96db1c141a
concourse/concourse-7.14.3+dev.1767116987.a785c6ea9.windows.amd64.zip:
  size: 250630302
  object_id: 121d5114-a35d-4c62-4071-44e385ff7e1e
  sha: sha256:fe0c9956c0569b3434cab9f4d2df690c57948e5a88963d0ee98011a596177e54
