btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3-rc.43+31f911818.linux.amd64.tgz:
  size: 936855051
  object_id: ebcca839-6969-4aaf-73c2-04c7c20a3fc5
  sha: sha256:4de91014c4573314c14dac0e28ed9204abf1175a6959e80c8e41786ab28a519b
concourse/concourse-7.14.3-rc.43+31f911818.windows.amd64.zip:
  size: 244411948
  object_id: 3cec13d9-2319-4529-7a6a-0ff8c6875d81
  sha: sha256:6f762451af39c17e8478de792272d3d6b728401f806bdd629f034765d824cec7
