btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.39+e9b986ce9.linux.amd64.tgz:
  size: 937760249
  object_id: 09bc30db-e417-4ba7-422f-8b5ea49b06fc
  sha: sha256:2a5e4700ac6aa9c1d86ade76b6dece13756769402f056761e5db1de932bbcd47
concourse/concourse-7.14.4-rc.39+e9b986ce9.windows.amd64.zip:
  size: 244430796
  object_id: 2cbceb10-5830-43ae-58e9-be738047053d
  sha: sha256:3e3ecffb77b0b1890aedc3d166d3d08eadb13675ccee7c54e3d3e3e25d6b4eca
