btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1768527123.e81401c0b.linux.amd64.tgz:
  size: 929183323
  object_id: cecb4e01-4f8e-4e5a-5f9f-f419af677d0e
  sha: sha256:a87c4576fa96909f0449a5016f34ca5752c8635666df436a0fe5cfe7ca36d114
concourse/concourse-8.0.0+dev.1768527123.e81401c0b.windows.amd64.zip:
  size: 241532861
  object_id: c68fa909-d610-42e9-5066-e5f8ffadf6c9
  sha: sha256:73c90eac75a4923862d29c7e6dc75d12819c1f7f88f07fe6aee4089ea5eb96de
