btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765821036.a785c6ea9.linux.amd64.tgz:
  size: 951740987
  object_id: 90a83fbc-0371-47c5-4b4c-e535a1ce8f5d
  sha: sha256:36a52c881c5f2c3737664f8e831b487c19428eda8c1b76df6147df3d3e6e2890
concourse/concourse-7.14.3+dev.1765821036.a785c6ea9.windows.amd64.zip:
  size: 250630354
  object_id: d8f89ddc-3aa1-469d-48b1-4233bc1406a3
  sha: sha256:69dca1165159248f7066ac24bfc52a941a9d8498237bf727d031cfcb8f85b235
