btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.44+e9b986ce9.linux.amd64.tgz:
  size: 937607869
  object_id: 6a98c4a4-55d5-441f-7af0-22e693a55ee4
  sha: sha256:e062464f44e8efab9429ba2c47641674f129c279a8649b6b7c28763b1033e12f
concourse/concourse-7.14.4-rc.44+e9b986ce9.windows.amd64.zip:
  size: 244431117
  object_id: 0f459913-d47f-458f-4a70-ae3db35fcd4a
  sha: sha256:4973903150bd32c705a2f76b2ff973f6e1c89a3d0b4b5263ec2268f5d21e7cd8
