btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1763060550.a17a43056.linux.amd64.tgz:
  size: 958605347
  object_id: a6728879-4313-4061-56f8-85113b64357f
  sha: sha256:6b81f7334dd4a02662e4c2a541df6155e612b193c6fa0bd96f93bcfbfbfeb947
concourse/concourse-7.13.2+dev.1763060550.a17a43056.windows.amd64.zip:
  size: 249619858
  object_id: 18af02b1-1d78-4907-7d1c-54d79e0a86e6
  sha: sha256:a929a75fcd2fa28feea5c62ecf1b24cf8dc55915b08cde7713249a2e4f053019
