btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1762729048.c67692d7e.linux.amd64.tgz:
  size: 956774381
  object_id: 1a7a363f-89e6-4cd3-7252-7fa59d2762da
  sha: sha256:9ede5e1b8dd9091862dc7e9e0944f369009ff4f7fa945ea0268566726b9fe1ec
concourse/concourse-7.13.2+dev.1762729048.c67692d7e.windows.amd64.zip:
  size: 249593464
  object_id: 2dbfb5cf-2355-4ffc-7a5d-574ba0ac339d
  sha: sha256:7c3cbd049b53b6b8b4a83770f9cea554591ca08702c9dd3f24ce4984c797ceb0
