btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3-rc.45+31f911818.linux.amd64.tgz:
  size: 936067164
  object_id: 5fd76064-a4e1-4c66-7744-f0453387fc13
  sha: sha256:b45258ee5b5489d0b00af645ab5504190ca32b710cc0a9f00ee7b219e6d9f5e3
concourse/concourse-7.14.3-rc.45+31f911818.windows.amd64.zip:
  size: 244413208
  object_id: 27ee4f85-9436-48b4-7186-511b83311e65
  sha: sha256:55a5ae9837bd992e355c0adb9b6169c40d8bc20b78c476b391c0aceb97963fe7
