btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3-rc.48+944f5f010.linux.amd64.tgz:
  size: 936066697
  object_id: 315e01b4-67cc-4a8a-7faf-0b1f61ddd96b
  sha: sha256:aeb51fb15012bea28feb1bfa19bb28569f41d944fb7c064d9b49d95846db6fa4
concourse/concourse-7.14.3-rc.48+944f5f010.windows.amd64.zip:
  size: 244412769
  object_id: cdbbfe19-f0c4-494f-48e6-af817563812c
  sha: sha256:f1dcd6d010466c178cb7b6c313c06d4577551ca842ced0612fcbef2954e1c0ee
