btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1768023018.a785c6ea9.linux.amd64.tgz:
  size: 937712672
  object_id: c34c62af-ed46-4b2a-4a81-d188d0a88154
  sha: sha256:6131475a8f1933f91aebe27df0a20d151ccbae3f1666f14f3aaaad09f6683200
concourse/concourse-7.14.3+dev.1768023018.a785c6ea9.windows.amd64.zip:
  size: 250629864
  object_id: 1cd105ca-6f1a-4ae8-4a6a-7860a3fee254
  sha: sha256:bee6cca5ab91f0700d55a0933703793666374e671232fdc91e637178e950249b
