btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1770233878.ebefbc998.linux.amd64.tgz:
  size: 920679806
  object_id: 5fbe91e2-431d-4cd8-7995-09eb72618ac5
  sha: sha256:a447191034df4cf5d2e1011dd5fa600c6b7582583aaba5550218b589cb91df8e
concourse/concourse-8.0.1+dev.1770233878.ebefbc998.windows.amd64.zip:
  size: 244269759
  object_id: 109278cb-ab03-4281-43d2-5b1cceb408a0
  sha: sha256:b6c40cd7f9a10e2f94c45d9a911b7f9e8553ee6254c5418933ab619ea56084e0
