btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1766431471.a785c6ea9.linux.amd64.tgz:
  size: 951851179
  object_id: 062dabdc-abca-4c15-4920-d8d123d47a30
  sha: sha256:ae34de6661f14189236104df5fb85d4daf5b6e5187c44b49b69565c44392707b
concourse/concourse-7.14.3+dev.1766431471.a785c6ea9.windows.amd64.zip:
  size: 250630202
  object_id: 92602d9a-7529-4399-4419-d168df912073
  sha: sha256:e41bd86e9aec89cd9108e67025abafe1d4225179e3d482813276930fdfb47c29
