btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1766433372.a785c6ea9.linux.amd64.tgz:
  size: 951850780
  object_id: f3ab4188-32da-4973-504a-74787f866774
  sha: sha256:3c32ece51cdbb92a24842e33ccdfec45d8494d0bf7ce2b577a53e887a6f50da2
concourse/concourse-7.14.3+dev.1766433372.a785c6ea9.windows.amd64.zip:
  size: 250629848
  object_id: 56adb01e-0ca8-43f3-6e35-d010f1bac44a
  sha: sha256:de53e0d217c42af7be378053fd4047ccd0a1eeef48f2b5a73868a635aed72cfe
