btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1769209632.f6795d8b5.linux.amd64.tgz:
  size: 929214416
  object_id: c459ceb9-5e56-40e9-43df-142dc55843fa
  sha: sha256:8821c764121f1bad8ba341403254d65a2439c9221a87f68f7392c9932debb003
concourse/concourse-8.0.0+dev.1769209632.f6795d8b5.windows.amd64.zip:
  size: 241530336
  object_id: 212d1b56-1b3b-4bd4-7ecb-12a59fc24639
  sha: sha256:551d21701c05a814f43e8edb5c216141c045206afa5ba3938ebc49ace274de9e
