btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1768020787.a785c6ea9.linux.amd64.tgz:
  size: 937660186
  object_id: 3ca717ad-d493-4aac-448d-6497f52d3044
  sha: sha256:fb8bd1c64e165cff4eb15c40434ca741fdd4d207b4edb04a347ec3a73d7a773f
concourse/concourse-7.14.3+dev.1768020787.a785c6ea9.windows.amd64.zip:
  size: 250629532
  object_id: e4ad40a2-f03e-43f4-5426-9eab82474bb9
  sha: sha256:59a98f22949d6b26286eb60e4d9ccfbdc57c95664696609f0d9c46d873132392
