btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3-rc.44+31f911818.linux.amd64.tgz:
  size: 936065570
  object_id: 801e0e0c-92e9-458f-4ed8-e1ffb60964e9
  sha: sha256:8e5311115aad61a66e34db0ddf0b3a40f0f16b09b05bdd4aec81373de33dee3f
concourse/concourse-7.14.3-rc.44+31f911818.windows.amd64.zip:
  size: 244412628
  object_id: 0daa8616-e7b8-4a4e-4533-5d56f9a7d34b
  sha: sha256:058ecee28c1ec706582f7c5afe1f36a8b5ccc20cbcad6ca993345915b090e31c
