btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.4+34f038301.linux.amd64.tgz:
  size: 936049611
  object_id: 2d133450-effd-457d-7942-328af20f45f1
  sha: sha256:49617162524b34c458568ff26b59b74f6b1c03d1f5ed4924e3007c378d5f7c45
concourse/concourse-7.14.4-rc.4+34f038301.windows.amd64.zip:
  size: 244412926
  object_id: b96c9109-c850-4f4f-5723-95a3b1745481
  sha: sha256:cc775b503c4976627fc67702825ba00e061a1a310b643fa09d5cff05dc911b44
