btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1763681466.750ce8b64.linux.amd64.tgz:
  size: 959112814
  object_id: 59f09170-6cf2-4de1-5c4b-07540dee8d7b
  sha: sha256:ab93bc8035732567ba37752c00007ec3013b24faa441333b0632c744f96379b4
concourse/concourse-7.13.2+dev.1763681466.750ce8b64.windows.amd64.zip:
  size: 249623656
  object_id: 3fedd68c-6af4-45a4-6dcb-df3940a77332
  sha: sha256:374631b1dfd2c38e930579bdd22c9794f4a1dd0c243d5b346465cc000f0030b2
