btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.6+34f038301.linux.amd64.tgz:
  size: 936063933
  object_id: 2194043c-a6b4-40ea-6ffa-a9bdb5baaf83
  sha: sha256:8f1d0e5c1ef74047074776c0091a34e511fa44511e2094a8e2f60c3e0964d86b
concourse/concourse-7.14.4-rc.6+34f038301.windows.amd64.zip:
  size: 244412658
  object_id: 417b9b16-0d19-4da9-48f3-2a729e78c264
  sha: sha256:07690d970c3ecff65b5cfd79085a624fc3eea7e8deaf2e213bab20418fa67e35
