btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.31+e9b986ce9.linux.amd64.tgz:
  size: 937613145
  object_id: b4eb270d-7b3c-4302-432d-3ac2cd30c809
  sha: sha256:df028bfe3e8d14e0dec726c57ec28e841b6fcb24655a33df15343160b4bc752c
concourse/concourse-7.14.4-rc.31+e9b986ce9.windows.amd64.zip:
  size: 244430297
  object_id: 4749f2e9-830f-46a9-5547-ba175293f954
  sha: sha256:c07f0473fd3d44e3b938499c17b08b7eeca12a02bbee2935d8dba8cbfc36ce24
