btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.13+34f038301.linux.amd64.tgz:
  size: 936637970
  object_id: 896a9da0-a3ab-4edf-77ce-80a4edb7ffaf
  sha: sha256:8dd3197ca604f0ff620a391fbda0ad25512cf1f9a096668c8a00cecb7884229a
concourse/concourse-7.14.4-rc.13+34f038301.windows.amd64.zip:
  size: 244413349
  object_id: ae5efe6c-df2e-49dc-71e8-47c9f328233e
  sha: sha256:1725078e26fdfa2c4476faded9d9e9292326b5b0a769508110285a276f9c03cd
