btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765277754.eaf0ff37f.linux.amd64.tgz:
  size: 952112872
  object_id: 4145c48f-63aa-4ba8-6e15-f475bd60861d
  sha: sha256:8ac597c4b5593a3183eebd68805f2ea338777a4083628501d11e1e59e842310d
concourse/concourse-7.14.3+dev.1765277754.eaf0ff37f.windows.amd64.zip:
  size: 250606572
  object_id: cecde6eb-caef-4de8-44f5-e7f1b07b99c0
  sha: sha256:34e23b1c2e18dab9e10e16eb9938a9d3375dcea585d2ef7aa819825aee45b942
