btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.10+34f038301.linux.amd64.tgz:
  size: 936194612
  object_id: 3b47da32-3d24-4566-5356-19adde222bdf
  sha: sha256:6934c7e4567c2006258765326ffd62d56b118d43dbe4b7aca8ccbe428499d595
concourse/concourse-7.14.4-rc.10+34f038301.windows.amd64.zip:
  size: 244412473
  object_id: 93636e49-4951-460e-5ac2-15f334ba1e1d
  sha: sha256:7ded52b522a469d89e5dccdf242035f693bae1751a21fadc4a3ce00f30ca3bde
