btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.2+dev.1771541913.25b021b05.linux.amd64.tgz:
  size: 918929035
  object_id: c444f687-197e-41f0-4320-d91565600e25
  sha: sha256:88873d555f4dd06944cddaf81cd39de65f15a5704b0c8768cf61c95346239db9
concourse/concourse-8.0.2+dev.1771541913.25b021b05.windows.amd64.zip:
  size: 251879937
  object_id: b0f42aa0-b991-42d4-7cbf-f3ea12dcf6a1
  sha: sha256:f649127a0defca298971141fee2a157affc5c55dd88645b5882cfbfcde2a986b
