btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767745441.a785c6ea9.linux.amd64.tgz:
  size: 938050992
  object_id: 6d27ff9c-4ac7-42f9-6f69-09bb09d24b99
  sha: sha256:53e9bff4ebe6c1bbc3ef421a27b8f3451f81e6ddd73da85d2243f3b56391d39e
concourse/concourse-7.14.3+dev.1767745441.a785c6ea9.windows.amd64.zip:
  size: 250628959
  object_id: 3efe8cd4-9990-4b29-7214-c0cd02b360da
  sha: sha256:0cd725924d4976d158107be185ed92567a02ebeb33bf86ccedd7ae7e6bbacb11
