btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1763357594.eb5626ab9.linux.amd64.tgz:
  size: 959093005
  object_id: bb115bbe-9c51-47f8-55a5-206256af97e5
  sha: sha256:7fa5e4d599a0d850766104ebd340a2e4208e5ce00dc719ee6c1141aa48e7c215
concourse/concourse-7.13.2+dev.1763357594.eb5626ab9.windows.amd64.zip:
  size: 249620262
  object_id: 2a49c7b7-15c3-40aa-6331-edea0ea08998
  sha: sha256:b8593e7ebf4f4e63146d747951a779c52e20e0f4b62c2048b832a492a668da68
