btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1771440072.9b7f58d97.linux.amd64.tgz:
  size: 911059896
  object_id: fc58f5c4-c9ce-431e-4da0-4bce5f33eaed
  sha: sha256:c14b4fc66607748b595874ef62a9881b5473f897caa31815d607ace2d22f9aaa
concourse/concourse-8.0.1+dev.1771440072.9b7f58d97.windows.amd64.zip:
  size: 251697218
  object_id: c2014065-deed-4e9d-660b-fbfa051d44a5
  sha: sha256:ff0e71fa8dad986b8ba8fbac089e68b6e680a5c3702f202ca0c81e631e9c2807
