btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1764615821.e5d441113.linux.amd64.tgz:
  size: 962017943
  object_id: 9fc4be0c-9e4e-40fe-7dae-554ea674a3e3
  sha: sha256:359476eb2083926b74f5390c423b738c5a098f62986104b78ca456647102c4c5
concourse/concourse-7.13.2+dev.1764615821.e5d441113.windows.amd64.zip:
  size: 251204679
  object_id: 234c82ce-af01-41db-48b1-680b4a2e3223
  sha: sha256:e6115f837b23672390c522e7d2f6e3ff320a96fee311d71977592e10097be8b1
