btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1769516712.f6795d8b5.linux.amd64.tgz:
  size: 928967010
  object_id: 8c2988a6-2854-44d0-7787-fedbee5875bd
  sha: sha256:504074aa03375a9d544741189bc81e3892892e7393a81112d6590723ed25d521
concourse/concourse-8.0.0+dev.1769516712.f6795d8b5.windows.amd64.zip:
  size: 241529806
  object_id: d48bb34f-dd0f-4734-5340-3b3801d507cf
  sha: sha256:3e45c218ade9eda9f84e4c551d23a316aee4e7cb812ddc1d6c788681056c737b
