btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.20+34f038301.linux.amd64.tgz:
  size: 936649919
  object_id: ddcbaa8e-3227-41d8-401e-54657cd59514
  sha: sha256:4279691c5739e586ee6227085be9118497a0d6f5dc8df59a595225a35289df66
concourse/concourse-7.14.4-rc.20+34f038301.windows.amd64.zip:
  size: 244430643
  object_id: ef92b70d-f5af-45f8-65e7-36ff83d8a3ad
  sha: sha256:3566e3a72afd3f9865117b49302572d8a9c099402f65298da734984e530700b2
