btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.35+e9b986ce9.linux.amd64.tgz:
  size: 937598463
  object_id: 69ad95de-3717-43ec-735f-b1694a3187b8
  sha: sha256:f94a2065ef677c6ae68127886e522858a0f2d526a518c754004497059cb30770
concourse/concourse-7.14.4-rc.35+e9b986ce9.windows.amd64.zip:
  size: 244431204
  object_id: 9f6fd100-6adb-4167-417d-8c564a40a981
  sha: sha256:47ba1e75b622721e47da5908cfe8e748bee88aa1f468af447714c1fe5721a3d9
