btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765262788.eaf0ff37f.linux.amd64.tgz:
  size: 952117760
  object_id: 66136030-2008-49b0-6cd9-64bd19b94e47
  sha: sha256:42daea92069e0403fec8ec6672114c0c588ad0bdd719d5bba0f56d56ce535734
concourse/concourse-7.14.3+dev.1765262788.eaf0ff37f.windows.amd64.zip:
  size: 250606857
  object_id: 7f37412a-320c-4d64-5d16-7b11f89f2763
  sha: sha256:2fef3d37cc536415c6089f1b68277472df901e890215de467d658a55cba15325
