btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1768426305.e81401c0b.linux.amd64.tgz:
  size: 929208380
  object_id: 662e7e02-4a85-45ee-7f59-b2731bff6493
  sha: sha256:117cb12e778fe03eac673c90f805f11a3599e624ed59a0b4a046d3dd402b0659
concourse/concourse-7.14.3+dev.1768426305.e81401c0b.windows.amd64.zip:
  size: 241499350
  object_id: a7282d48-38d1-454f-5530-65d1ee2e64d1
  sha: sha256:6660349b6152baad8e13c201b04c9e9edf0188c29db6803e08eb7b9073d258fd
