btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1770531566.a1bf74e1c.linux.amd64.tgz:
  size: 920910277
  object_id: 324a6a72-1060-4b7c-4068-0d684a7041e3
  sha: sha256:77eb057c77c39afc54a17ad0123824b7efcc6196ed54ffc433edef442b0261ee
concourse/concourse-8.0.1+dev.1770531566.a1bf74e1c.windows.amd64.zip:
  size: 244281073
  object_id: 0155d7dd-c64f-4c38-4f54-d6b2de958b5c
  sha: sha256:7657f0b074615157b5cf699c0bfb430aa4b313994862d5f0aa742972d038b182
