btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765799914.79e7b5411.linux.amd64.tgz:
  size: 951855135
  object_id: f37dae48-04e2-43a3-7647-b2928e9f902f
  sha: sha256:9624272736c937511d9531a3895738dfaff0178c50ec4d28cf76bdac4a1f7274
concourse/concourse-7.14.3+dev.1765799914.79e7b5411.windows.amd64.zip:
  size: 250633279
  object_id: 0113bee1-5518-4c01-5480-8554fc0fb629
  sha: sha256:f24816aaadbfbac5153d9dc423464f233d5038665b77fecf4c4ce40b74e59f93
