btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.43+e9b986ce9.linux.amd64.tgz:
  size: 937613097
  object_id: d8a80550-3d3e-493d-6676-f8e3a2887edb
  sha: sha256:85108836d25d21c80223554adea4cfd42aac7a640630b9e8b06966a600fc8df1
concourse/concourse-7.14.4-rc.43+e9b986ce9.windows.amd64.zip:
  size: 244430760
  object_id: 8efa2dce-e208-4c77-7570-a4375bae73a2
  sha: sha256:11cc0f6b25808b46ce3f8eae4b4cd29372462e1e2212d2afd2e624dca8cd188f
