btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.25+e9b986ce9.linux.amd64.tgz:
  size: 936685346
  object_id: 6e5a2234-c0ae-485e-4993-6f1939446d13
  sha: sha256:e48e335c1afd36c6e88e1ff77c5e1e09d2fb5584827bb815aa463d196967699a
concourse/concourse-7.14.4-rc.25+e9b986ce9.windows.amd64.zip:
  size: 244426920
  object_id: 9dd1b820-6059-4ea0-758a-5c80a2f40d16
  sha: sha256:09e66675ed73aa3b13683cbd1d4a9e8d5a40acd8b4dcd31d7e823660450d1f41
