btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.46+e9b986ce9.linux.amd64.tgz:
  size: 937723665
  object_id: 7ceb2da0-4e10-41dc-59e2-3660ae0ce1b8
  sha: sha256:4a8192b2565b837707dbcdce37d2429123c575ce99c2b219f06d7ff2b2e2e85b
concourse/concourse-7.14.4-rc.46+e9b986ce9.windows.amd64.zip:
  size: 244427182
  object_id: 2f7b86fb-114b-4fa4-5bdd-d6a889a75c7a
  sha: sha256:086f4106283e9ee97d3971daf175f135ac996b95e37876280d0857a93b9ae372
