btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.23+e9b986ce9.linux.amd64.tgz:
  size: 936631776
  object_id: ffa035e1-cb03-4a79-66a1-ec9644852d66
  sha: sha256:2d9eb75e1af53469a3c2b433d2e7fb2084f67089a5e281b3fcc6b5d94c3d6388
concourse/concourse-7.14.4-rc.23+e9b986ce9.windows.amd64.zip:
  size: 244427660
  object_id: 2b0b433a-d6f3-4523-7005-22b00d918161
  sha: sha256:59226fe8c34401e4afa933da94406ee66140aa0a11cf1b5f6b154b9b6fe70081
