btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1770708251.a1bf74e1c.linux.amd64.tgz:
  size: 920867062
  object_id: 72c52d73-8f78-4d51-61fa-f021c9f18ebd
  sha: sha256:f146b6cf2c470fec49f5156b8ce9e76d15afe2adb2e7dc9a9ac64cbc8631890c
concourse/concourse-8.0.1+dev.1770708251.a1bf74e1c.windows.amd64.zip:
  size: 244280416
  object_id: 98cf3e5a-f366-4521-7c93-e8b96d0527e5
  sha: sha256:baeb9a66f123c833c86edda49e24e1e6a34899b68825015e2939a0175d0bc561
