btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.2-rc.28+caf63a4d6.linux.amd64.tgz:
  size: 933311784
  object_id: 29eb7a31-0f11-454d-4f34-643c23bdf8c6
  sha: sha256:9c21202a371b48b49cbe1f94248260f8f61c881fefe7d20e79f8fd0f64301b49
concourse/concourse-8.0.2-rc.28+caf63a4d6.windows.amd64.zip:
  size: 248930680
  object_id: adfdeda0-c1c6-42a9-73e3-994de7e2b078
  sha: sha256:0f43d9e9db6c67240d0e47e09413822b8f65ff69c5eea2318eaf60817a17b194
