btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1770256208.a1bf74e1c.linux.amd64.tgz:
  size: 920717500
  object_id: 08c15fdc-45c7-4da6-76db-83d3bbecb1c3
  sha: sha256:c53e233b9020b3f5f96ca16c1d34fd3a31ba53a1c4cd8b7c1c4c6e0e3c52ae24
concourse/concourse-8.0.1+dev.1770256208.a1bf74e1c.windows.amd64.zip:
  size: 244280584
  object_id: e2f71507-3024-428f-50e6-e80fa4cbd019
  sha: sha256:3a971edfed7772cdbbe1763820980d94bacd59c020137d402aa4a95f4df54894
