btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1768530259.e81401c0b.linux.amd64.tgz:
  size: 929177355
  object_id: 414761ea-c448-4df9-662e-6e2514e612d2
  sha: sha256:88395bf2e30fd3d2d094b3fd718b660c3cddb8a12060ff15033224d549a262d1
concourse/concourse-8.0.0+dev.1768530259.e81401c0b.windows.amd64.zip:
  size: 241532765
  object_id: 3ea94622-d00d-4000-72e8-36ca329b2783
  sha: sha256:d3c5a5e3019e3fb9dbf683396b8a98b0442414b355cd9ccfa08e519361dca400
