btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.2+dev.1771868495.cd61cbd24.linux.amd64.tgz:
  size: 918958553
  object_id: 25c82e4e-ae6b-4c57-4db4-14da5d605f88
  sha: sha256:f6484922fb610e2d87b68f7e6feeda5e3a97a85b243dc11c60113cf112cc47d0
concourse/concourse-8.0.2+dev.1771868495.cd61cbd24.windows.amd64.zip:
  size: 251882618
  object_id: dd614c7b-5b72-4d76-6661-2500c817eec3
  sha: sha256:63c2b7b1757b26090de14817c2de8a00766f45f93dcf5e319f88a1591bfaf1b0
