btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1769497791.f6795d8b5.linux.amd64.tgz:
  size: 928959969
  object_id: d2d75996-0855-4e5d-4c85-013e39c6bb01
  sha: sha256:477504ebda147a059ca928eaf52390645b12a5bb4dfc071332773a1e34908ca0
concourse/concourse-8.0.0+dev.1769497791.f6795d8b5.windows.amd64.zip:
  size: 241530428
  object_id: a387bc5a-fae9-49cc-5c75-534f7f772884
  sha: sha256:c9e8938802d4d653b6f1f9eb4e97bea07d93c8f6d6035efaa68de10c4125f70a
