btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0-rc.3+94166a751.linux.amd64.tgz:
  size: 929118277
  object_id: 3df8f7ab-d95d-4f08-4d68-67c555119329
  sha: sha256:bce3f099900cc4e7f439c47fed4b43fbe3181a2132368e6e5520f2eef36bafee
concourse/concourse-8.0.0-rc.3+94166a751.windows.amd64.zip:
  size: 241494783
  object_id: 49bfda6c-5d5f-4543-5e5e-39a6ae0dc970
  sha: sha256:10198380e04890d3b0ecfc264da8ef22bbe1728ff46d7598f8b7286823ef215d
