btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765342169.432a9fbb1.linux.amd64.tgz:
  size: 952136403
  object_id: b9162aee-2453-4b36-63c4-26c7c9e5a1c1
  sha: sha256:6084f65e37cbe613d1ff64f0d468bcd358667be287a9fa32280e282039f3a3b4
concourse/concourse-7.14.3+dev.1765342169.432a9fbb1.windows.amd64.zip:
  size: 250606916
  object_id: 9076f346-be5d-4379-7cbf-9d6aae58bc0a
  sha: sha256:c0edee543f150b98eee4c280365f5e9a3ead22ef8f8443e2130b17def8a20060
