btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1762846657.c67692d7e.linux.amd64.tgz:
  size: 956966294
  object_id: d6784cfa-3c18-4ab9-5e48-6f8aac8615a2
  sha: sha256:46b7f1fcbdb1439a85af419c32dc4cfe7650c0072341274c06cfbbe6f77803c8
concourse/concourse-7.13.2+dev.1762846657.c67692d7e.windows.amd64.zip:
  size: 249594011
  object_id: 7a3a96b2-412c-42ce-4430-3bc012739117
  sha: sha256:b4cb5e2869b6c04e1410718cf35a1de2dd7ea2605960b3c06b37b0610dade32b
