btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.12+34f038301.linux.amd64.tgz:
  size: 936252634
  object_id: d9a28d10-b948-4b1f-5f53-0053b3841963
  sha: sha256:621cae7a6d885fabfa22ad66f6e07c62c06526a0756555c28ddafab7f93262ae
concourse/concourse-7.14.4-rc.12+34f038301.windows.amd64.zip:
  size: 244412142
  object_id: 1609fa3c-3b7b-405f-79e4-082e91029475
  sha: sha256:5c03f7b741f0504933266bd2c408d427ff8784ee69423b50dcb710cf150d8a4e
