btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.27+e9b986ce9.linux.amd64.tgz:
  size: 936632226
  object_id: 92adc320-ed0e-4e9a-4ccc-21d187f422f8
  sha: sha256:0cae6c6c0fb68e58363f076c6deb279349ce53b08e05ff76cb857e3663f3ff5d
concourse/concourse-7.14.4-rc.27+e9b986ce9.windows.amd64.zip:
  size: 244426965
  object_id: 11abc1b1-a37c-473e-4a10-575c1b60b2db
  sha: sha256:e83d5925f5cac40b1358efd609ac3b87248a2859423725b8877a4c3b8946cb20
