btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1763182188.97393cea9.linux.amd64.tgz:
  size: 959066219
  object_id: ae4db5c1-652c-4eae-7085-41097c23e7e6
  sha: sha256:1b01be3f7632ce78d78e657bbd6f804ea657d8db196fa6ff1fe0fe590622a497
concourse/concourse-7.13.2+dev.1763182188.97393cea9.windows.amd64.zip:
  size: 249626162
  object_id: aa879b58-e2f7-4971-65f5-b3bf1bb91b8a
  sha: sha256:01063232b03c68d740231c790a7100f6f37f032f6509257fb4ac1a593e31bdd5
