btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1768865327.5be51422f.linux.amd64.tgz:
  size: 929230677
  object_id: 5d0a4760-9863-43f3-7376-132819b16d18
  sha: sha256:4baf2abba0040f6da35e976e9cfc5c0fecc858c324153a03e5a77c4c7c2e414f
concourse/concourse-8.0.0+dev.1768865327.5be51422f.windows.amd64.zip:
  size: 241536128
  object_id: 24ea4a39-b662-4ea4-5df2-eaa05f735135
  sha: sha256:a06e704903629553676a8685d6a11bad183280b3ce3f9a31837114fe02c83b94
