btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.2+944f5f010.linux.amd64.tgz:
  size: 936123844
  object_id: 4f581d68-0405-46bd-48a9-3a2aaaf8bd0e
  sha: sha256:c37617d77fab7cbb2dacecedb69a92b82b3592971f752e4e82e4c4e2f6ad73e2
concourse/concourse-7.14.4-rc.2+944f5f010.windows.amd64.zip:
  size: 244413013
  object_id: 23b81071-28da-4f86-4263-a5c20ecc77bf
  sha: sha256:0ac9bc8a7301aecb96fbd02ad138d44129683af48c8f628ededa1030db74f2fb
