btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765260674.eaf0ff37f.linux.amd64.tgz:
  size: 952118035
  object_id: 303bccde-9515-4118-6397-e30bc49010cf
  sha: sha256:684a769b602efd94cd0725c08b5c7f2704ee3b78e607a52e1c864c2c284ac09a
concourse/concourse-7.14.3+dev.1765260674.eaf0ff37f.windows.amd64.zip:
  size: 250606921
  object_id: ef88f3f4-daee-4239-5286-6934d1c4e0b7
  sha: sha256:92dc5f93a230e9118ce0fca6f4c830d8c3f71af845065f37337cc643a2f67d7e
