btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765223763.3e9f601fe.linux.amd64.tgz:
  size: 951098469
  object_id: e6cba1f6-ea59-4990-6824-66aa859a30e1
  sha: sha256:4a7b8fc5ec7bcb133cea3a42a82e556b7e9e7a9fb20987723ec2e6636d588046
concourse/concourse-7.14.3+dev.1765223763.3e9f601fe.windows.amd64.zip:
  size: 250607746
  object_id: 4bbe9c3f-f24f-4170-5120-9bbf0c6e0008
  sha: sha256:8bd796398aa0447380a94688fa101e9b09f7e00d54e89cc4c2638aab0bb7d2ee
