btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767810367.a785c6ea9.linux.amd64.tgz:
  size: 938017630
  object_id: 6484ec95-f7f6-4b94-5afb-2e6c510228e8
  sha: sha256:85cd59d6886df0f010399259baa49d803ffc1cbe5415f306156ecc56a240cc03
concourse/concourse-7.14.3+dev.1767810367.a785c6ea9.windows.amd64.zip:
  size: 250629495
  object_id: 05580e1f-5958-407e-5681-f2d4d36085e9
  sha: sha256:b84ee74b16f4529570ceec8836383f5a80950bd5e2afb3cefd523dcd44fd3ce1
