btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765226328.eaf0ff37f.linux.amd64.tgz:
  size: 951102503
  object_id: 491c400c-e7aa-4129-425e-9f19b4731b34
  sha: sha256:725fde19e772df3641331f1eea43c9b723d7319a97a3756689289bc94851a84c
concourse/concourse-7.14.3+dev.1765226328.eaf0ff37f.windows.amd64.zip:
  size: 250607384
  object_id: 07661c23-fd2a-4beb-4698-b59c5c9842b4
  sha: sha256:722959a40ff256783120ec28fd9b63f902e5df26c506bd772abe82b049502ae8
