btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1768520560.e81401c0b.linux.amd64.tgz:
  size: 929216331
  object_id: 4b2019d3-ce44-4aec-725e-f7f72579abb5
  sha: sha256:505df43fc408478ee46d084248906c3beb6c90a889c02292a63508e01dfc4e2d
concourse/concourse-8.0.0+dev.1768520560.e81401c0b.windows.amd64.zip:
  size: 241533223
  object_id: de5bca8a-00bd-45d7-5f9b-9df0915736ec
  sha: sha256:9bae38ab26a402afc3d619981153c3041b31592052743038718a26f8c792e242
