btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765823451.a785c6ea9.linux.amd64.tgz:
  size: 951668274
  object_id: eaf6c84d-f5fb-48b3-5d8c-9129455cf742
  sha: sha256:0c3f33d3dd5db2b98a8a9ca30d876b552a6725901a5f7ce88ffefe9a19b4649e
concourse/concourse-7.14.3+dev.1765823451.a785c6ea9.windows.amd64.zip:
  size: 250629167
  object_id: 2c896f54-e5e7-47ce-4ee0-bf8edef9ae3a
  sha: sha256:8d866196876b023e99c346fb166b2143c072bb0ec87dfe4f038c60a0ca3033d6
