btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1762725854.c67692d7e.linux.amd64.tgz:
  size: 956838593
  object_id: d2bacf70-5fdb-4e1b-4bbf-ddd15ee4ed64
  sha: sha256:d0e6fa2d4b28f0c4fa26425593ba18c98c6fe61fb4fdceb90c5001f71767491b
concourse/concourse-7.13.2+dev.1762725854.c67692d7e.windows.amd64.zip:
  size: 249594424
  object_id: 8fd3bbc4-f5c4-48a4-4485-2a6d95605c4f
  sha: sha256:44323d3af4b34fd9a50de284461e33bc40f47bf511149b15675b34885632f975
