btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1769144480.f6795d8b5.linux.amd64.tgz:
  size: 929288121
  object_id: 7086fc66-d2a4-42dd-7fb9-65a485d20a5c
  sha: sha256:b239faa55211ccc3a251eccf824cf93e7ea37cab0e2dabb80354605eea49aa4a
concourse/concourse-8.0.0+dev.1769144480.f6795d8b5.windows.amd64.zip:
  size: 241529940
  object_id: 4555c696-0812-4f44-608e-eeff0803d46c
  sha: sha256:9677eb3e44de21f1f133c100013ddc9acf02f47a15a99f1b9217dc8c8fce2ff5
