btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1770751451.a1bf74e1c.linux.amd64.tgz:
  size: 920826207
  object_id: dcbe1a58-5a88-48d1-614e-9861564e3044
  sha: sha256:757346a1909ee181aa4acf210fb1815a8ed2b4aad667fd80667ab3166cd1d36b
concourse/concourse-8.0.1+dev.1770751451.a1bf74e1c.windows.amd64.zip:
  size: 244280279
  object_id: 5b6a1356-7467-4772-66c4-7c1bcd24268a
  sha: sha256:9ea20ee0295d97dcf4eb2734f5f83ac04472d083494066837a88082912e8ec93
