btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1765806574.79e7b5411.linux.amd64.tgz:
  size: 951733612
  object_id: 56b9aef6-d15c-4d13-4aa0-38e64764adb9
  sha: sha256:bf350411d01dd440de0a0b7b0a89a40cddeca05f0f114fef0a91d45d7e3e41e2
concourse/concourse-7.14.3+dev.1765806574.79e7b5411.windows.amd64.zip:
  size: 250632778
  object_id: bee0f5a1-9a65-421f-45dc-da260762d045
  sha: sha256:062ebfafaac55e0ea087e50bef80e8cd0bf130e83926a766624ec8f6c9d5ff4d
