btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1768967227.d5bf4d4d8.linux.amd64.tgz:
  size: 929228900
  object_id: 12834b49-afdd-40a2-4776-45b49e6a98c3
  sha: sha256:c17be5968e9c59a6790334727083b7a6ae1096a99fd90a757eb215bfa19842d5
concourse/concourse-8.0.0+dev.1768967227.d5bf4d4d8.windows.amd64.zip:
  size: 241533803
  object_id: 782f80e8-1861-4358-7163-0e285e5135df
  sha: sha256:00ef4512984d80f472ef06d38c0318e4566671d6600fcfa6065fa7c1d5921a06
