btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1769564195.f6795d8b5.linux.amd64.tgz:
  size: 928991926
  object_id: 164a7daa-d8de-4c47-5038-1b830010063f
  sha: sha256:d79397351c946c4e1f040a174bd2187c8382c3df88693d9d5ebfe616e21b8ea1
concourse/concourse-8.0.0+dev.1769564195.f6795d8b5.windows.amd64.zip:
  size: 241530556
  object_id: 339f2785-fcbe-46ff-6d1f-2f0e5827ce9b
  sha: sha256:8ded08e07e4ee4951a6f24551a7b2fc9ec4a4d985d0df97710003e074b228be3
