btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1768094663.1b6b459c1.linux.amd64.tgz:
  size: 929162194
  object_id: fa58cec3-8d60-43d2-67e0-49d23a06609f
  sha: sha256:47ee48ebdab4b9822c8790d6a044e2e2c65356ab964a16c0ba092974f291e6f2
concourse/concourse-7.14.3+dev.1768094663.1b6b459c1.windows.amd64.zip:
  size: 241500359
  object_id: 120456f1-3126-4553-7555-8ae6bd19f7c1
  sha: sha256:32c44bc45653d4c7198a192c7541733f16266c6057c02cc499613104f8332272
