btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1768369034.e81401c0b.linux.amd64.tgz:
  size: 929171537
  object_id: 5220c1d1-1cfc-4e88-45fb-f0c422e991ba
  sha: sha256:3c13ddc98c6602e1de0f39c397398168ac4899e8ecb13fddbe1518ffc25c2db7
concourse/concourse-7.14.3+dev.1768369034.e81401c0b.windows.amd64.zip:
  size: 241499228
  object_id: fe8cb352-82b4-49f1-664a-ffc053b65c65
  sha: sha256:49504a83302e9f75f15a74baa0735cbebf084cb2b3514c538d223d63b3d06f7a
