btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1-rc.8+e81401c0b.linux.amd64.tgz:
  size: 929269692
  object_id: ee218ee0-b872-4ff3-6e3e-a9cff2c892b3
  sha: sha256:09320f64ce7291b6fbb880a688685cf42af2d92f93fa0f0e53a76d732b6d4799
concourse/concourse-8.0.1-rc.8+e81401c0b.windows.amd64.zip:
  size: 241533700
  object_id: 917986cc-4889-40cc-5f93-f85980008995
  sha: sha256:b2b7d058c6bd2136ac02fdd3081daa6f228df9396eccfdf0975cc6fd68258509
