btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1770236721.ebefbc998.linux.amd64.tgz:
  size: 920685349
  object_id: 773c5d04-1622-440b-40d5-35042456aea9
  sha: sha256:131aa61637a4478776426efac7133df12312b77a2fd41157ba6d8cb0c98e04e6
concourse/concourse-8.0.1+dev.1770236721.ebefbc998.windows.amd64.zip:
  size: 244269921
  object_id: eae560c8-0021-45b2-7772-a5b6589fb6df
  sha: sha256:3b2674096764e77891204e99d9ffb596f24b3c4fd1cbd0e0792d21f8e3c7c83b
