btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1769495373.f6795d8b5.linux.amd64.tgz:
  size: 929129841
  object_id: 9cfbfec3-c631-4f49-45de-c96008e43fcd
  sha: sha256:56b5545603d59b2fa1352f1e32205146dec0d524a5914815487a178a63916f18
concourse/concourse-8.0.0+dev.1769495373.f6795d8b5.windows.amd64.zip:
  size: 241529726
  object_id: d16cfacc-8f61-409f-6de5-24673613e735
  sha: sha256:0308df636f9883e0772729ddc742d286bdab07e7152cbde6b2192a8226a42de9
