btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.4-rc.3+944f5f010.linux.amd64.tgz:
  size: 936218376
  object_id: 9af07ce4-6cec-4694-52b4-3435cd0d0eb5
  sha: sha256:d721c73b0241b55f595372f6fed3c7cc336143a9646f3060eaed7cff0fe9d01e
concourse/concourse-7.14.4-rc.3+944f5f010.windows.amd64.zip:
  size: 244412548
  object_id: 56980a7f-305d-4cb0-4f02-fac05c34a6bf
  sha: sha256:6505e20dc63db3b1b7c9c3d997297bb1115abeb5b1cd174e4077e0cd968440e7
