btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.0+dev.1769211480.f6795d8b5.linux.amd64.tgz:
  size: 929210060
  object_id: a26bf0cd-43eb-4c8f-7ea3-deb21a5574a9
  sha: sha256:d824ba38431ff9f7471c971735ff45633d6708615a3b6665b6304748eb7804f4
concourse/concourse-8.0.0+dev.1769211480.f6795d8b5.windows.amd64.zip:
  size: 241530213
  object_id: 1217de85-b55d-4cb1-47ff-4167e7f51be7
  sha: sha256:37cee1c25f90c0cf86d9949354ed0b23a5e28954c351ea756d0390aa4724a763
