btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1763186898.97393cea9.linux.amd64.tgz:
  size: 959115326
  object_id: 3ab43637-d44e-47a3-5b75-cf5d7e965aff
  sha: sha256:c3a8a37f1fd59069181fe54ab26afb23d18521d4fac72a40c472a7869b05e56e
concourse/concourse-7.13.2+dev.1763186898.97393cea9.windows.amd64.zip:
  size: 249625948
  object_id: 71fbbd93-8fd7-4069-68e4-bb59e8657b44
  sha: sha256:49a6f405f1ae1078900db1da862c3232ee0581345edf1378c28384e3124f9b97
