btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-8.0.1+dev.1771445702.2947128ee.linux.amd64.tgz:
  size: 912746228
  object_id: 49a8948f-7877-4e90-4f8c-cd8d30856ad2
  sha: sha256:c22b5baf43faba2aef5610988c7df7368a4f846fe80768070f2337e68fc4e309
concourse/concourse-8.0.1+dev.1771445702.2947128ee.windows.amd64.zip:
  size: 251696576
  object_id: c343d350-73c1-4c8d-4b61-a68cec8d57b8
  sha: sha256:d4ffcb4048323243ed41820c2b5b64921ef2e3dd618f27b0cca0d8be9d995a27
