btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.13.2+dev.1763622257.9b448e724.linux.amd64.tgz:
  size: 959077615
  object_id: 8032b579-9b14-4300-627d-2bb1520a6408
  sha: sha256:42a0fbeacb3f8b6172e75fb1547b872cd8b5c7f07db4a29c53d4d0eabf35fd48
concourse/concourse-7.13.2+dev.1763622257.9b448e724.windows.amd64.zip:
  size: 249625412
  object_id: a3537f1c-1141-4ba6-73a3-99e5e009f299
  sha: sha256:61b216bb4bda295f94aa53c73bf06758b53d2081b2bdc9ef6433bb45815a1fe4
