btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767733634.a785c6ea9.linux.amd64.tgz:
  size: 937644665
  object_id: 19a41a50-5b3e-435f-750a-7d4efc6d689b
  sha: sha256:5440d80fbe2f447678951cdca8fcb276c87edeadad95e7d50a1f4a827d7ccce8
concourse/concourse-7.14.3+dev.1767733634.a785c6ea9.windows.amd64.zip:
  size: 250629442
  object_id: 7d967913-d26f-428b-5b3a-b824475b17e6
  sha: sha256:4dc5347ab9bb36e36609426d5e19d516e45363a798a478b337629eac1f9fef8a
