btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
concourse/concourse-7.14.3+dev.1767093480.a785c6ea9.linux.amd64.tgz:
  size: 951877790
  object_id: cb394795-dc84-4e86-5193-10788af3deb5
  sha: sha256:a7e80477adc91a169bbf7c7378295a69111024cbd2ede41cdc6166ef02e13e04
concourse/concourse-7.14.3+dev.1767093480.a785c6ea9.windows.amd64.zip:
  size: 250629700
  object_id: bf3a203c-e60b-43f4-46ab-9877d1f1b437
  sha: sha256:b6fb834257ee4d78a1eb266af41fa94a774d72f4788696b6c911233f3cd5b8ef
